services:
  physai:
    environment:
      - MUJOCO_GL=${MUJOCO_GL:-egl}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, graphics]
